### ISSUE TITLE
seeing error logging about task exceptions

### ISSUE THREAD

**Issue by aftertommy** [scottyphillips/echonetlite_homeassistant#116]
I've seen a lot of exceptions that take place each time I try to control the AC. Here is an example:

```
2022-09-23 10:27:16.700 DEBUG (MainThread) [custom_components.echonetlite] ECHONETLite Message Received - Processed data is {'EHD1': 16, 'EHD2': 129, 'TID': 0, 'SEOJGC': 1, 'SEOJCC': 48, 'SEOJCI': 1, 'DEOJGC': 14, 'DEOJCC': 240, 'DEOJCI': 1, 'ESV': 115, 'OPC': [{'EPC': 128, 'PDC': 1, 'EDT': b'0'}]}
2022-09-23 10:27:16.700 DEBUG (MainThread) [custom_components.echonetlite]
ECHONETlite polling update data:
 - Operation status (0x80): On
 - Operation status (0x80): On
 - Air flow rate setting (0xa0): high
 - Automatic swing of air flow setting (0xa3): vert-horiz
 - Operation mode setting (0xb0): cool
 - Set temperature value (0xb3): 26
 - Measured value of room relative humidity (0xba): 75
 - Measured value of room temperature (0xbb): 24
 - Measured outdoor air temperature (0xbe): 23
 - Measured instantaneous power consumption (0x84): 100
 - Measured cumulative power consumption (0x85): 659300

2022-09-23 10:27:16.700 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pychonet/echonetapiclient.py", line 86, in echonetMessageReceived
    await update_func(isPush)
  File "/config/custom_components/echonetlite/__init__.py", line 329, in async_update_callback
    await update_func(isPush)
  File "/config/custom_components/echonetlite/sensor.py", line 282, in async_update_callback
    changed = self._state_value != self._instance._update_data[self._op_code]
KeyError: 180
 ```

Here is another:
```
2022-09-23 10:28:36.868 DEBUG (MainThread) [custom_components.echonetlite] ECHONETLite Message Received - Processed data is {'EHD1': 16, 'EHD2': 129, 'TID': 36615, 'SEOJGC': 14, 'SEOJCC': 240, 'SEOJCI': 1, 'DEOJGC': 14, 'DEOJCC': 240, 'DEOJCI': 1, 'ESV': 115, 'OPC': [{'EPC': 213, 'PDC': 4, 'EDT': b'\x01\x05\xfd\x01'}]}
2022-09-23 10:28:36.868 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pychonet/echonetapiclient.py", line 79, in echonetMessageReceived
    if epc not in self._state[host]["instances"][seojgc][seojcc][seojci] or self._state[host]["instances"][seojgc][seojcc][seojci][epc] != opc["EDT"]:
KeyError: 14
2022-09-23 10:28:36.882 DEBUG (MainThread) [custom_components.echonetlite] ECHONETLite Message Received - Processed data is {'EHD1': 16, 'EHD2': 129, 'TID': 40711, 'SEOJGC': 14, 'SEOJCC': 240, 'SEOJCI': 1, 'DEOJGC': 14, 'DEOJCC': 240, 'DEOJCI': 1, 'ESV': 115, 'OPC': [{'EPC': 213, 'PDC': 4, 'EDT': b'\x01\x05\xfd\x01'}]}
2022-09-23 10:28:36.882 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pychonet/echonetapiclient.py", line 79, in echonetMessageReceived
    if epc not in self._state[host]["instances"][seojgc][seojcc][seojci] or self._state[host]["instances"][seojgc][seojcc][seojci][epc] != opc["EDT"]:
KeyError: 14
2022-09-23 10:28:38.242 DEBUG (MainThread) [custom_components.echonetlite] ECHONETLite Message Received - Processed data is {'EHD1': 16, 'EHD2': 129, 'TID': 39687, 'SEOJGC': 14, 'SEOJCC': 240, 'SEOJCI': 1, 'DEOJGC': 14, 'DEOJCC': 240, 'DEOJCI': 1, 'ESV': 115, 'OPC': [{'EPC': 213, 'PDC': 4, 'EDT': b'\x01\x05\xfd\x01'}]}
2022-09-23 10:28:38.242 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pychonet/echonetapiclient.py", line 79, in echonetMessageReceived
    if epc not in self._state[host]["instances"][seojgc][seojcc][seojci] or self._state[host]["instances"][seojgc][seojcc][seojci][epc] != opc["EDT"]:
KeyError: 14
```

I am not sure if this is related, but I've noticed that sometimes, `set_hvac_mode` service calls either don't take effect, or they take multiple minutes to do so. Meanwhile, setting the mode directly via the device appears to work fine? I'm not 100% certain about that -- I'm still trying to get clear repro, but the above logs appear to be pretty constant each time I try to interact with my echonet devices.

**Comment by nao-pon** [comment]
@aftertommy I'm still not sure what caused this issue, but I've made a fix in the master branch.

I would like you to use this master branch for verification.

**Comment by aftertommy** [comment]
@nao-pon I just tried the latest on the master branch, and I still appear to be getting errors. I redownloaded the integration on HACS using `master`, then restarted Home Assistant. From there I turned my Office AC to off. The following two error logs appeared:

```
Log Details (ERROR)


Logger: homeassistant.components.sensor
Source: custom_components/echonetlite/sensor.py:189 
Integration: Sensor (documentation, issues) 
First occurred: 10:28:29 AM (12 occurrences) 
Last logged: 10:28:29 AM

Error adding entities for domain sensor with platform echonetlite
Error while setting up echonetlite platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 691, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 777, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 388, in state
    value = self.native_value
  File "/config/custom_components/echonetlite/sensor.py", line 189, in native_value
    self._state_value = self._instance._update_data[self._op_code]
KeyError: 180
```

```
Log Details (ERROR)


 
This error originated from a custom integration.
Logger: homeassistant
Source: custom_components/echonetlite/select.py:132 
Integration: ECHONETLite (documentation, issues) 
First occurred: 10:28:29 AM (4 occurrences) 
Last logged: 10:28:40 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pychonet/echonetapiclient.py", line 90, in echonetMessageReceived
    await update_func(isPush)
  File "/config/custom_components/echonetlite/__init__.py", line 329, in async_update_callback
    await update_func(isPush)
  File "/config/custom_components/echonetlite/select.py", line 132, in async_update_callback
    changed = new_val and self._state_value != new_val
AttributeError: 'EchonetSelect' object has no attribute '_state_value'
```

**Comment by nao-pon** [comment]
I almost figured out the cause. I've updated the master branch, so please download it again and try it.

**Comment by aftertommy** [comment]
So far it seems to be ok.

**Comment by aftertommy** [comment]
Anything in particular you would like me to try?

**Comment by nao-pon** [comment]
Thanks for the verification! What about the `set_hvac_mode` service call? Did that delay go away?

**Comment by aftertommy** [comment]
It seems to be working now? I don't see error logging. I swear sometimes I have to call the service twice but it eventually goes through, and when it doesn't I don't see any logging at all. This is via the developer interface in the web frontend.

**Comment by nao-pon** [comment]
I don't have an actual air conditioner, so I checked it with the MoekadenRoom simulator, and the mode change service changes correctly in one go. Depending on the brand and model, it seems that it takes about 10 seconds for the request to be accepted. Is there a possibility of such a situation?

**Comment by aftertommy** [comment]
That could be. I’d be ok with considering this resolved — if I find something else I can refile. I really can’t thank you enough!On Oct 4, 2022, at 23:51, Naoki Sawada ***@***.***> wrote:﻿
I don't have an actual air conditioner, so I checked it with the MoekadenRoom simulator, and the mode change service changes correctly in one go. Depending on the brand and model, it seems that it takes about 10 seconds for the request to be accepted. Is there a possibility of such a situation?

**Comment by nao-pon** [comment]
Thanks! 👍
