### ISSUE TITLE
Won't start: 'ConfigEntries' object has no attribute 'async_setup_platforms'

### ISSUE THREAD

**Issue by kerryland** [scottyphillips/echonetlite_homeassistant#137]
This integration is no longer starting for me in 2023.5.4.
```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/echonetlite/__init__.py:134
Integration: ECHONETLite (documentation, issues)
First occurred: 12:13:51 AM (2 occurrences)
Last logged: 12:20:23 AM

Error setting up entry Mitsubishi Heatpump for echonetlite
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/echonetlite/__init__.py", line 134, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

**Comment by kerryland** [comment]
I just noticed that this integration wasn't listed on my HACS page. Weird. So I guess I was running an old version.

Anyway, I installed from HACS and all is working well now. Apologies, and thanks for such a handy bit of software!
