### ISSUE TITLE
Error when trying to update through HACS

### ISSUE THREAD

**Issue by aheath70** [scottyphillips/echonetlite_homeassistant#157]
Trying to install the latest version gbut getting the following error

```
2024-01-10 00:27:54.052 ERROR (MainThread) [custom_components.hacs] <Integration scottyphillips/echonetlite_homeassistant> GitHub returned HttpStatusCode.INTERNAL_SERVER_ERROR for https://api.github.com/repos/scottyphillips/echonetlite_homeassistant/git/trees/3.7.9
2024-01-10 00:27:54.359 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140288119138624] No manifest.json file found 'custom_components/None/manifest.json'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2149, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2186, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 882, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 952, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 161, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 465, in async_install_with_progress
    await self.async_install(version, backup)
  File "/config/custom_components/hacs/update.py", line 83, in async_install
    await self.repository.update_repository(force=True)
  File "/config/custom_components/hacs/utils/decorator.py", line 28, in wrapper
    result = await function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/repositories/integration.py", line 126, in update_repository
    if manifest := await self.async_get_integration_manifest():
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/repositories/integration.py", line 173, in async_get_integration_manifest
    raise HacsException(f"No {RepositoryFile.MAINIFEST_JSON} file found '{manifest_path}'")
custom_components.hacs.exceptions.HacsException: No manifest.json file found 'custom_components/None/manifest.json'

**Comment by scottyphillips** [comment]
Looks more like a HACS issue to me. `No manifest.json file found 'custom_components/None/manifest.json'` is the problem. Nothing echonetlite related in that code. This project has a manifest file. I suggest reinstalling HACS.

**Comment by aheath70** [comment]
Right, you are. Reinstallation of HACS resolved the issues. My bad!
