### ISSUE TITLE
Some Mitsubishi AC's not retrieving room/Ambient Temp

### ISSUE THREAD

**Issue by zuchie-star** [scottyphillips/echonetlite_homeassistant#64]
Firstly, thank you for this Integration. I Installed 3 x Mitsubishi MSZ-AP20VGD split system air conditioners with MAC-568IF-E wifi controls.

2 of the units integrate perfectly with HA with full control & ambient room temp readings, the third unit has full control - on/off , temp adjust etc. However will not retrieve the ambient room temp.

I have 2 x errors in the log;

"Logger: homeassistant
Source: custom_components/echonetlite/climate.py:177
Integration: ECHONETLite ([documentation](https://www.github.com/scottyphillips/echonetlite_homeassistant), [issues](https://github.com/scottyphillips/echonetlite_homeassistant/issues))
First occurred: February 17, 2022, 10:30:43 PM (178 occurrences)
Last logged: 1:27:43 AM
Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 735, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 574, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 298, in state_attributes
    if self.hvac_action:
  File "/config/custom_components/echonetlite/climate.py", line 177, in hvac_action
    if self._connector._update_data[ENL_HVAC_SET_TEMP] < self._connector._update_data[ENL_HVAC_ROOM_TEMP]:
TypeError: '<' not supported between instances of 'float' and 'NoneType' "

"Logger: homeassistant
Source: custom_components/echonetlite/sensor.py:145
Integration: ECHONETLite ([documentation](https://www.github.com/scottyphillips/echonetlite_homeassistant), [issues](https://github.com/scottyphillips/echonetlite_homeassistant/issues))
First occurred: 1:27:47 AM (341 occurrences)
Last logged: 4:17:44 AM
Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 735, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 572, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 371, in state
    value = self.native_value
  File "/config/custom_components/echonetlite/sensor.py", line 145, in native_value
    if self._instance._update_data[self._op_code] is None:
KeyError: 133"

Thanks

**Comment by scottyphillips** [comment]
Very odd. I could not explain why one unit in particular is not returning the room temperature readings other than to suggest going through the unit configuration and manual and confirming what is being configured to measure the room temperature. My ducted HVAC for example the ambient room temp can be measured from the control panel or the indoor unit. 

I have a few fixes in place for those particular error messages, but I wouldn't be able to tell you why 1 of 3 identical units is not correctly returning room temperature.

**Comment by zuchie-star** [comment]
Hi, thanks for getting back to me. Funnily enough, after a few HA reboots, all the units are working perfectly now within HA, not sure what the issue was, im still getting an error msg in the logs, however it is working now.

Thanks again

**Comment by scottyphillips** [comment]
What’s the error message?

**Comment by scottyphillips** [comment]
Can you update to latest release?

**Comment by zuchie-star** [comment]
Logger: homeassistant
Source: custom_components/echonetlite/sensor.py:145
Integration: ECHONETLite (documentation<https://www.github.com/scottyphillips/echonetlite_homeassistant>, issues<https://github.com/scottyphillips/echonetlite_homeassistant/issues>)
First occurred: February 21, 2022, 8:53:44 PM (45 occurrences)
Last logged: 3:20:17 PM

Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 735, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 572, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 371, in state
    value = self.native_value
  File "/config/custom_components/echonetlite/sensor.py", line 145, in native_value
    if self._instance._update_data[self._op_code] is None:
KeyError: 133


________________________________

**Comment by zuchie-star** [comment]
Just updated. No more errors.

Thank you very much
________________________________

**Comment by xbmcnut** [comment]
@zuchie-star Are they all still working under ECHONETLite version is 3.4.9 & HA Core version is 2022.5.3? I've just added four new units and only two are reporting sensor data like your issue but I see anything in the logs.

**Comment by zuchie-star** [comment]
Yes, mine are all working fine - 3 units reporting all A/C functions, ambient temps & cumulative power to the energy dashboard.
One of the units seems to draw power when it's off though, im not sure if its vampire power or  the integration.

Give your integration 24hrs and if they haven't registered, remove them and re-add the units

**Comment by zuchie-star** [comment]
sorry forgot to mention, im using ECHONETLite 3.4.9 & HA Core version is 2022.5.3 - same as you

**Comment by xbmcnut** [comment]
Cheers, appreciate the feedback. Deleting and re-adding now.
