### ISSUE TITLE
Mitsubishi Heatpump stuck  

### ISSUE THREAD

**Issue by droopanu** [scottyphillips/echonetlite_homeassistant#65]
Hello,

Every now and then I get one of my Mitsubishi heapumps stuck in a weird mode and I the integration fails to send anything to the heatpump, and only manages to read the state only from time to time:

2022-02-21 10:08:26 DEBUG (MainThread) [custom_components.echonetlite] pychonet version in use is 2.1.1
2022-02-21 10:08:26 DEBUG (MainThread) [custom_components.echonetlite] 000006010458d50afffea7a149013001 is the UID..
**2022-02-21 10:08:26 DEBUG (MainThread) [custom_components.echonetlite] Create new HomeAirConditioner instance at: 192.168.86.75
2022-02-21 10:08:26 DEBUG (MainThread) [custom_components.echonetlite] 000006010458d50afffea7a149013001 is the UID in ECHONET connector..
2022-02-21 10:08:26 DEBUG (MainThread) [custom_components.echonetlite] {'3047791cdc85358f02a45837ebbefa32': [], 'api': <pychonet.echonetapiclient.ECHONETAPIClient object at 0x7fef7c1ed940>} has already been setup..**
2022-02-21 10:08:26 DEBUG (MainThread) [custom_components.echonetlite] pychonet version in use is 2.1.1
2022-02-21 10:08:26 DEBUG (MainThread) [custom_components.echonetlite] 000006010458d50afffe9124d4013001 is the UID..
2022-02-21 10:08:26 DEBUG (MainThread) [custom_components.echonetlite] Create new HomeAirConditioner instance at: 192.168.86.82
2022-02-21 10:08:26 DEBUG (MainThread) [custom_components.echonetlite] 000006010458d50afffe9124d4013001 is the UID in ECHONET connector..
2022-02-21 10:08:27 DEBUG (MainThread) [custom_components.echonetlite] ['Off', 'medium-high', 'non-auto', 'not-used', 'central', 'left', 'fan_only', 20, 19, 126, 234600]
2022-02-21 10:08:27 DEBUG (MainThread) [custom_components.echonetlite] Plaform entry data - {'instances': [{'host': '192.168.86.82', 'eojgc': 1, 'eojcc': 48, 'eojci': 1, 'getmap': [128, 160, 176, 129, 161, 130, 131, 163, 179, 164, 133, 165, 134, 136, 137, 138, 154, 139, 187, 157, 158, 190, 143, 159], 'setmap': [128, 129, 143, 147, 160, 161, 163, 164, 165, 176, 179, 208], 'uid': '000006010458d50afffe9124d4013001', 'manufacturer': 'Mitsubishi'}]}
2022-02-21 10:08:27 DEBUG (MainThread) [custom_components.echonetlite.light] Number of light devices to be added: 0
2022-02-21 10:08:33 DEBUG (MainThread) [custom_components.echonetlite.sensor] setting up sensor {'instance': {'host': '192.168.86.82', 'eojgc': 1, 'eojcc': 48, 'eojci': 1, 'getmap': [128, 160, 176, 129, 161, 130, 131, 163, 179, 164, 133, 165, 134, 136, 137, 138, 154, 139, 187, 157, 158, 190, 143, 159], 'setmap': [128, 129, 143, 147, 160, 161, 163, 164, 165, 176, 179, 208], 'uid': '000006010458d50afffe9124d4013001', 'manufacturer': 'Mitsubishi'}, 'echonetlite': <custom_components.echonetlite.ECHONETConnector object at 0x7fef7c1c89d0>}
2022-02-21 10:08:33 DEBUG (MainThread) [custom_components.echonetlite.sensor] update flags for this sensor are [128, 160, 161, 163, 164, 165, 176, 179, 187, 190, 133]
2022-02-21 10:08:33 DEBUG (MainThread) [custom_components.echonetlite.sensor] This is an ECHONET climate device so only a few sensors will be created
**2022-02-21 10:08:39 DEBUG (MainThread) [custom_components.echonetlite] [False, False, False, False, False, False, False, False, False, False]
2022-02-21 10:08:39 DEBUG (MainThread) [custom_components.echonetlite] polling ECHONET Instance host 192.168.86.75 timed out - Retry 1 of 3
2022-02-21 10:08:39 DEBUG (MainThread) [custom_components.echonetlite] Number of missed ECHONETLite msssages since reboot is - 2
2022-02-21 10:08:46 DEBUG (MainThread) [custom_components.echonetlite] [False, False, False, False, False, False, False, False, False, False]
2022-02-21 10:08:46 DEBUG (MainThread) [custom_components.echonetlite] polling ECHONET Instance host 192.168.86.75 timed out - Retry 2 of 3
2022-02-21 10:08:46 DEBUG (MainThread) [custom_components.echonetlite] Number of missed ECHONETLite msssages since reboot is - 4
2022-02-21 10:08:52 DEBUG (MainThread) [custom_components.echonetlite] [False, False, False, False, False, False, False, False, False, False]
2022-02-21 10:08:52 DEBUG (MainThread) [custom_components.echonetlite] polling ECHONET Instance host 192.168.86.75 timed out - Retry 3 of 3
2022-02-21 10:08:52 DEBUG (MainThread) [custom_components.echonetlite] Number of missed ECHONETLite msssages since reboot is - 6
2022-02-21 10:08:52 DEBUG (MainThread) [custom_components.echonetlite] Plaform entry data - {'instances': [{'host': '192.168.86.75', 'eojgc': 1, 'eojcc': 48, 'eojci': 1, 'getmap': [128, 160, 176, 129, 161, 130, 131, 163, 179, 164, 133, 165, 134, 136, 137, 138, 154, 139, 187, 157, 158, 190, 143, 159], 'setmap': [128, 129, 143, 147, 160, 161, 163, 164, 165, 176, 179, 208], 'uid': '000006010458d50afffea7a149013001', 'manufacturer': 'Mitsubishi'}]}
2022-02-21 10:08:52 DEBUG (MainThread) [custom_components.echonetlite.sensor] setting up sensor {'instance': {'host': '192.168.86.75', 'eojgc': 1, 'eojcc': 48, 'eojci': 1, 'getmap': [128, 160, 176, 129, 161, 130, 131, 163, 179, 164, 133, 165, 134, 136, 137, 138, 154, 139, 187, 157, 158, 190, 143, 159], 'setmap': [128, 129, 143, 147, 160, 161, 163, 164, 165, 176, 179, 208], 'uid': '000006010458d50afffea7a149013001', 'manufacturer': 'Mitsubishi'}, 'echonetlite': <custom_components.echonetlite.ECHONETConnector object at 0x7fef7c1c86d0>}**
2022-02-21 10:08:52 DEBUG (MainThread) [custom_components.echonetlite.sensor] update flags for this sensor are [128, 160, 161, 163, 164, 165, 176, 179, 187, 190, 133]
2022-02-21 10:08:52 DEBUG (MainThread) [custom_components.echonetlite.sensor] This is an ECHONET climate device so only a few sensors will be created
2022-02-21 10:08:52 DEBUG (MainThread) [custom_components.echonetlite.light] Number of light devices to be added: 0
2022-02-21 10:09:27 DEBUG (MainThread) [custom_components.echonetlite] ['Off', 'medium-high', 'non-auto', 'not-used', 'central', 'left', 'fan_only', 20, 19, 126, 234600]
**2022-02-21 10:09:58 DEBUG (MainThread) [custom_components.echonetlite] [False, False, False, False, False, False, False, False, False, False]
2022-02-21 10:09:58 DEBUG (MainThread) [custom_components.echonetlite] polling ECHONET Instance host 192.168.86.75 timed out - Retry 1 of 3
2022-02-21 10:09:58 DEBUG (MainThread) [custom_components.echonetlite] Number of missed ECHONETLite msssages since reboot is - 8
2022-02-21 10:10:05 DEBUG (MainThread) [custom_components.echonetlite] [False, False, False, False, False, False, False, False, False, False]
2022-02-21 10:10:05 DEBUG (MainThread) [custom_components.echonetlite] polling ECHONET Instance host 192.168.86.75 timed out - Retry 2 of 3
2022-02-21 10:10:05 DEBUG (MainThread) [custom_components.echonetlite] Number of missed ECHONETLite msssages since reboot is - 10
2022-02-21 10:10:11 DEBUG (MainThread) [custom_components.echonetlite] [False, False, False, False, False, False, False, False, False, False]
2022-02-21 10:10:11 DEBUG (MainThread) [custom_components.echonetlite] polling ECHONET Instance host 192.168.86.75 timed out - Retry 3 of 3
2022-02-21 10:10:11 DEBUG (MainThread) [custom_components.echonetlite] Number of missed ECHONETLite msssages since reboot is - 12**
2022-02-21 10:10:27 DEBUG (MainThread) [custom_components.echonetlite] ['Off', 'medium-high', 'non-auto', 'not-used', 'central', 'left', 'fan_only', 20, 19, 126, 234600]

**2022-02-21 10:13:55 DEBUG (MainThread) [custom_components.echonetlite] ['Off', 'auto', 'non-auto', 'not-used', 'upper', 'center', 'heat', 20, 19, 126]
2022-02-21 10:13:55 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 735, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 526, in async_update_ha_state
    self._async_write_ha_state()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 572, in _async_write_ha_state
    state = self._stringify_state()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 545, in _stringify_state
    if (state := self.state) is None:
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/sensor/__init__.py", line 371, in state
    value = self.native_value
  File "/home/homeassistant/.homeassistant/custom_components/echonetlite/sensor.py", line 145, in native_value
    if self._instance._update_data[self._op_code] is None:
KeyError: 133**

**Comment by scottyphillips** [comment]
The ECHONET protocol is connectionless by nature and it is designed to fire off the commands and basically hope for the best. There is no guarantee that a response would be received. Most of the debug messages are suggesting that the polling is failing from time to time. It could be something as simple as a weak Wi-Fi signal. As for the error message, I figured out the root cause of the KeyError based upon the logs you provided. Under certain conditions ( > 10 attributes) the update data was dropping the op codes from the _update_data dict when the second part of a batch ECHONET transaction failed. I have made a tweak to how the update works and that message should not appear again.

**Comment by droopanu** [comment]
I'm pretty sure it's not wifi. I can ping the device with no packet loss.
Also using the wifi control app on the local network works without any issues.

I believe the issue is with the wifi module getting in a weird state every now and then, and it stops responding to most echonet messages.
I've seen it a few times. Most of the time I was able to fix it by turning echonet off and on. But this time it's been in this state for a few days with no luck :(

On a unrelated note, I just noticed that the official wifi control app bypasses the cloud when on the same wifi network .

**Comment by scottyphillips** [comment]
Have you tried fully powercycling the AC from say the circuit breaker to reset the wifi module?

**Comment by droopanu** [comment]
I've been avoiding that as the power switch is in a very awkward place.

The reason I initially opened this issue, is that it looks like the setup/discovery of the device is usually successful when hass/integration loads. The following set/get state tend to fail most of the time.

I was wondering if there is something in the setup that could trigger this issue sometimes.

**Comment by scottyphillips** [comment]
No

**Comment by droopanu** [comment]
cool, thank you!

**Comment by droopanu** [comment]
I did a bit more digging, and I believe it is a weird issue with the integration.
I added the faulty heatpump to another instance of homeassistant, and it works without any issues.
Then I tried the following on the instance that has issues and it did not fix it:
- Restarted the heatpump from the power
- removed the heatpump integration and tried to re-add. I get the following error:
2022-02-22 11:57:22 DEBUG (MainThread) [custom_components.echonetlite.config_flow] IP address is 192.168.86.75
2022-02-22 11:57:22 DEBUG (MainThread) [custom_components.echonetlite.config_flow] API listener has already been setup previously..
2022-02-22 11:57:22 DEBUG (MainThread) [custom_components.echonetlite.config_flow] Beginning ECHONET node discovery
2022-02-22 11:57:23 DEBUG (MainThread) [custom_components.echonetlite.config_flow] ECHONET Node Discovery Successful!
2022-02-22 11:57:23 DEBUG (MainThread) [custom_components.echonetlite.config_flow] instance is 1
2022-02-22 11:57:26 DEBUG (MainThread) [custom_components.echonetlite.config_flow] 192.168.86.75 - ECHONET Instance 1-48-1 map attributes discovered!
2022-02-22 11:57:29 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/srv/homeassistant/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/srv/homeassistant/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/forwarded.py", line 220, in forwarded_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/config/config_entries.py", line 164, in post
    return await super().post(request, flow_id)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/data_entry_flow.py", line 111, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/data_entry_flow.py", line 252, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/home/homeassistant/.homeassistant/custom_components/echonetlite/config_flow.py", line 116, in async_step_user
    self.instance_list = await validate_input(self.hass, user_input)
  File "/home/homeassistant/.homeassistant/custom_components/echonetlite/config_flow.py", line 73, in validate_input
    uid = state['instances'][eojgc][eojcc][instance][ENL_UID]
KeyError: 131


I'll try and completely reinstall the integration to see if it fixes it.

**Comment by droopanu** [comment]
Ok, redownloading the integration from HACS has fixed the issue...
