### ISSUE TITLE
Async callback functionality not working

### ISSUE THREAD

**Issue by scottyphillips** [scottyphillips/echonetlite_homeassistant#98]
@nao-pon can you please take a look at this:
```
2022-07-09 10:38:26 DEBUG (MainThread) [custom_components.echonetlite.climate] Updated fan mode is: low
2022-07-09 10:38:26 DEBUG (MainThread) [custom_components.echonetlite]
ECHONETlite polling update data:
- Operation status (0x80): Off
- Operation status (0x80): Off
- Air flow rate setting (0xa0): Invalid setting
- Operation mode setting (0xb0): invalid_setting
- Set temperature value (0xb3): 19
- Measured value of room temperature (0xbb): 18
- Measured outdoor air temperature (0xbe): 10
2022-07-09 10:38:26 DEBUG (MainThread) [custom_components.echonetlite.climate] Called async_update_callback on boof.
Changed: True
Update data: {128: 'Off', 160: 'Invalid setting', 176: 'invalid_setting', 179: 19, 187: 18, 190: 10}
Old data: {128: 'Off', 160: 'medium-high', 176: 'invalid_setting', 179: 19, 187: 18, 190: 10}
2022-07-09 10:38:26 DEBUG (MainThread) [custom_components.echonetlite.climate] Updated fan mode is:
2022-07-09 10:38:26 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140027908565472] ''
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 193, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
await service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 717, in _handle_entity_call
await result
File "/config/custom_components/echonetlite/climate.py", line 240, in async_set_fan_mode
await self._connector._instance.setFanSpeed(fan_mode)
File "/usr/local/lib/python3.10/site-packages/pychonet/HomeAirConditioner.py", line 318, in setFanSpeed
return self.setMessage(ENL_FANSPEED, FAN_SPEED[fan_speed])
KeyError: ''

```
I have had to disable some of that async functionality that is causing the issues above in last commit; once i did that it starts working properly again
https://github.com/scottyphillips/echonetlite_homeassistant/commit/218dd8d7c9feb070e8b6c5c4bc8c5dfa1cf9cad4

**Comment by nao-pon** [comment]
This is still my guess, but parameters not included in the notification map may not have to update self._state.

for example...

```diff
diff --git a/pychonet/echonetapiclient.py b/pychonet/echonetapiclient.py
index 2627f66..99133b4 100644
--- a/pychonet/echonetapiclient.py
+++ b/pychonet/echonetapiclient.py
@@ -50,9 +50,10 @@ class ECHONETAPIClient:
                         epc
                     ] = EPC_SUPER_FUNCTIONS[epc](opc["EDT"])
                 else:
-                    if (epc not in self._state[host]["instances"][seojgc][seojcc][seojci] or self._state[host]["instances"][seojgc][seojcc][seojci][epc] != opc["EDT"]):
-                        updated = True
-                    self._state[host]["instances"][seojgc][seojcc][seojci][epc] = opc["EDT"]
+                    if not isPush or epc in self._state[host]["instances"][seojgc][seojcc][seojci].get(ENL_STATMAP, []):
+                        if (epc not in self._state[host]["instances"][seojgc][seojcc][seojci] or self._state[host]["instances"][seojgc][seojcc][seojci][epc] != opc["EDT"]):
+                            updated = True
+                        self._state[host]["instances"][seojgc][seojcc][seojci][epc] = opc["EDT"]
 
         # Call update callback functions
         if updated and key in self._update_callbacks:
```

**Comment by nao-pon** [comment]
By the way, in the verification in MoekadenRoom, the room temperature, the set temperature and power of the air conditioner are updated by polling, and the others are functioning normally by push update.

**Comment by scottyphillips** [comment]
My HVAC does not push any notifications at all irrespective of the notification map.

**Comment by scottyphillips** [comment]
Are you running MoekadenRoom on a seperate instance to your home assistant stack?

**Comment by scottyphillips** [comment]
i think i am making some progress on this: ESV get response messages (0x71) are causing the problem

**Comment by nao-pon** [comment]
Congratulations!

As a reminder, 0x71 is the response to the 0x61 (Set C) request, is it okay to ignore it altogether?

**Comment by nao-pon** [comment]
After checking the specifications, it seems that there is no problem.

The 0x71 response does not include the EDT value.

**Comment by nao-pon** [comment]
Since the 0x71 response does not have the EDT value set, I think it is better not to set `self._state[host]["instances"][seojgc][seojcc][seojci][epc]`.
for example...

```python
                else: # ignore ESV set response only (ESV 0x71)
                    if esv != 0x71:
                        if epc not in self._state[host]["instances"][seojgc][seojcc][seojci] or self._state[host]["instances"][seojgc][seojcc][seojci][epc] != opc["EDT"]:
                            updated = True
                        self._state[host]["instances"][seojgc][seojcc][seojci][epc] = opc["EDT"]
```

**Comment by nao-pon** [comment]
In addition ... The specification says that in a 0x71 or 0x51 response, the PDC should be set to 0 and no EDT should be added for the successfully accepted property, so it might be a good idea to check the value of the PDC.

```python
                else: # ignore response if OPC["PDC"] = 0 (for ESV 0x51, 0x71)
                    if opc["PDC"] > 0:
                        if epc not in self._state[host]["instances"][seojgc][seojcc][seojci] or self._state[host]["instances"][seojgc][seojcc][seojci][epc] != opc["EDT"]:
                            updated = True
                        self._state[host]["instances"][seojgc][seojcc][seojci][epc] = opc["EDT"]
```

**Comment by nao-pon** [comment]
Again, except for 0x72, 0x73, 0x74 responses, it returns the requested EDT for non-requestable requests and should be ignored regardless of the PDC value.

Also, in 0x52, 0x53 responses it will only get EDT for the accepted properties, so in 0x52, 0x53 responses he should look up the value of PDC.

**Comment by nao-pon** [comment]
I created a PR. https://github.com/scottyphillips/pychonet/pull/48
